### ISSUE TITLE
你好，有训练好的模型吗？

### ISSUE THREAD

**Issue by U-c207Pr4f57t9** [Zongwei97/HIDANet#3]

**Comment by Zongwei97** [comment]
你好，
谢谢你对我们文章的关注。非常不好意思这么晚回复。
我是存训练好的模型，但是因为是稍微早期一些的ckpt，和文章中每个模块的名称有出入，所以就先不放了。
一般情况下，重新训练一遍也能得到相近的结果。
我们已经公开了saliency maps，基本包含了大部分RGB-D SOD的数据集。
你也可以直接使用。
谢谢
