### ISSUE TITLE
When the salient maps will be public?

### ISSUE THREAD

**Issue by thinh-huynh-re** [Zongwei97/HIDANet#4]
Hi @Zongwei97 , thank you for your amazing work.
I would like to see the salient maps so I can analyze the results further. 
When will the salient maps on these datasets (DES,  NLPR, NJU2K, STERE, SIP) be public?

**Comment by Zongwei97** [comment]
Hi,
Thanks for your interest in our work.
I have just uploaded the saliency maps. You can check on the read.me.

**Comment by thinh-huynh-re** [comment]
Thank you very much,
I'm able to calculate the exact results as reported in the paper.

![Screenshot from 2023-07-10 11-22-12](https://github.com/Zongwei97/HIDANet/assets/126648805/cc3439d0-717b-4a30-bd8f-413dbd464070)
