### ISSUE TITLE
The input image has only 1 different values. It can not be thresholded in 3 classes

### ISSUE THREAD

**Issue by xueseqingniao** [Zongwei97/HIDANet#5]
你好 我在使用你的代码中的regionst = np.digitize(t[0], bins=threshold_multiotsu(t[0]))时，出现The input image has only 1 different values. It can not be thresholded in 3 classes

**Comment by Zongwei97** [comment]
您好，
感谢对我们工作的关注。
我猜测您可能使用了2985数据集训练，如Issue #2 中一样。
我觉得可能是深度图的原因， 因为multiotsu自带的算法可能无法对一些只有一个值的深度图进行threshold。
可以看一下报错的深度图片。
如文章所述，我们是在2185上训练的，没有遇到过这个问题。
